# Generated by Django 3.1.1 on 2020-10-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201022_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountproduct',
            old_name='dicount',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='productoption',
            table='product_options',
        ),
    ]
