# Generated by Django 3.1.2 on 2020-10-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20201027_1608'),
        ('product', '0002_auto_20201023_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOption',
        ),
    ]
