# Generated by Django 3.1.1 on 2020-10-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_morningdeliveryarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='sales_limit',
            field=models.IntegerField(default=0),
        ),
    ]
