# Generated by Django 3.1.2 on 2020-10-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_product_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='productoption',
            table='products_options',
        ),
    ]
