# Generated by Django 3.1.2 on 2020-10-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201022_1701'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productoption',
            table='product_options',
        ),
    ]
