# Generated by Django 3.1.1 on 2020-10-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
    ]
