# Generated by Django 3.1.1 on 2020-10-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201021_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
