# Generated by Django 3.1.2 on 2020-10-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_shoppingbasket_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='title',
        ),
    ]
