# Generated by Django 3.1.2 on 2020-10-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201023_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='option',
            field=models.IntegerField(default=0),
        ),
    ]
