# Generated by Django 3.1.1 on 2020-10-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_product_question'),
        ('user', '0003_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frequently_purchased_product',
            field=models.ManyToManyField(related_name='frequently_purchased_products', through='user.FrequentlyPurchasedProduct', to='product.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(related_name='orders', through='user.Order', to='product.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', through='user.Review', to='product.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_basket',
            field=models.ManyToManyField(related_name='shopping_baskets', through='user.ShoppingBasket', to='product.Product'),
        ),
    ]
