# Generated by Django 3.1.2 on 2020-10-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201021_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbasket',
            name='option',
            field=models.IntegerField(default=0),
        ),
    ]
