# Generated by Django 3.1.2 on 2020-10-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_review_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='iamge_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
