# Generated by Django 3.1.2 on 2020-10-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_shoppingbasket_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlypurchasedproduct',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
