# Generated by Django 3.1.2 on 2020-10-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_review_iamge_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='iamge_url',
            new_name='image_url',
        ),
    ]
