# Generated by Django 3.1.2 on 2020-10-26 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_order_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ranks',
            },
        ),
        migrations.RemoveField(
            model_name='userrank',
            name='name',
        ),
        migrations.AddField(
            model_name='userrank',
            name='rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.rank'),
        ),
    ]
