# Generated by Django 3.1.2 on 2020-10-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201026_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrank',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.rank'),
        ),
    ]
