# Generated by Django 3.1.2 on 2020-10-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201026_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrank',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='userrank',
            name='user',
        ),
        migrations.AddField(
            model_name='userrank',
            name='name',
            field=models.CharField(default='웰컴', max_length=50),
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
