# Generated by Django 3.1.2 on 2020-10-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20201027_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='option',
        ),
    ]
