# Generated by Django 3.1.2 on 2020-10-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_shoppingbasket_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbasket',
            name='is_option',
            field=models.BooleanField(default=False),
        ),
    ]
