# Generated by Django 3.1.2 on 2020-10-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201023_1336'),
        ('user', '0016_shoppingbasket_is_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='is_option',
        ),
        migrations.CreateModel(
            name='ShoppingBasketOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productoption')),
                ('shoppingbasket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.shoppingbasket')),
            ],
            options={
                'db_table': 'shopping_basket_options',
            },
        ),
    ]
