# Generated by Django 3.1.2 on 2020-10-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20201027_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='option',
        ),
        migrations.DeleteModel(
            name='ShoppingBasketOption',
        ),
    ]
