# Generated by Django 3.1.2 on 2020-10-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20201027_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlypurchasedproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
